name: Weekly Snow Data
on:
  schedule:
    - cron: '0 0 * * 1' # UTC 00:00 Mon = JST 09:00 Mon
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Generate weekly JSON
        run: node scripts/fetch-weekly.js
      - name: Commit & push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(data): update weekly snow JSON'
          file_pattern: public/data/latest.json
